
# 应用服务 WEB 访问端口
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: future_user_system



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 未来聊天系统
    description: "接口文档"
    email: 3310787712@qq.com
    concat: 古白
    url: https://docs.xiaominfo.com
    version: v1.0
    group:
      test1:
        group-name: 业务
        api-rule: package
        api-rule-resources:
          - com.mysystem.futuresystemhd.controller
          - om.mysystem.futuresystemhd.information





